name: Workflow name

on: push

permissions:
  contents: read

jobs:
  continue1:
    name: Run test with multiple configurations
    runs-on: ubuntu-latest
    strategy:
      matrix:
        number_of_cities: [30]
        segment: [12]
        iteration: [151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200]
        data_set: ["RC101_0.5.dat", "RC101_2.dat"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install requirements
        run: pip install -r requirements.txt
        
      - name: Run main.py ITE-3 for each iteration
        run: python test_similarity.py
        env:
          NUMBER_OF_CITIES: ${{ matrix.number_of_cities }}
          DATA_SET: ${{ matrix.data_set }}
          SEGMENT: ${{ matrix.segment }}
          ITERATION: ${{ matrix.iteration }}
      - name: Upload result Excel file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: json1-results-${{ matrix.number_of_cities }}-${{ matrix.data_set }}-${{ matrix.segment }}-iter-${{ matrix.iteration }}
          path: Random_*_CL2.xlsx
  
  summary:
    name: Summary results
    needs: continue1
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: .
          merge-multiple: true
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: excel-results-summary
          path: Random_*_CL2.xlsx
