name: Run stuff

on: push

permissions:
  contents: read

jobs:
  test:
    name: Run test
    runs-on: ubuntu-lates

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Python test
        run: python 1_0.3.py
